export const REQUEST_TRUCKS = 'REQUEST_TRUCKS'
export const RECEIVE_TRUCKS = 'RECEIVE_TRUCKS'
export const UPDATE_TRUCKS = 'UPDATE_TRUCKS'

export const TOGGLE_MODAL = 'TOGGLE_MODAL'
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'

export const REQUEST_LOCATION = 'REQUEST_LOCATION'
export const RECEIVE_LOCATION = 'RECEIVE_LOCATION'
export const FAIL_LOCATION = 'FAIL_LOCATION'
